package br.com.wmw.lavenderepda.notification;

public enum LavendereNotificationConstants {
	
	ATUALIZACAO_CLIENTE,
	REL_DIFERENCA_PEDIDO,
	ATUALIZACAO_APP,
	OPEN_RECADO,
	OPEN_NOVIDADE,
	OPEN_RELINDICADOR,
	OPEN_ITEMCUSTO,
	OPEN_RELINFOENTREGA,
	OPEN_RELCLINAOATENDIDO,
	OPEN_NOVOCLIANALISE,
	OPEN_RELMETAVENDAS,
	OPEN_LISTNOVOSAC,
	LIST_PEDIDO_NOVOPEDIDO_DIF,
	AVISO_CLIENTE_CHURN,
	SYNC_ANDAMENTO,
	LOGIN_DADOS_SUCESS,
	LOGIN_DADOS_ERROR,
	VALIDADATAHORASERVIDOR,
	OPEN_DETALHES_SYNC,
	RECEBE_CARGA_FOTOPRODUTO,
	MEDIA_DOWNLOAD,
	PEDIDO_ENVIOBLOQUEADO,
	STOP_SYNC_MEDIA,
	CATALOGO_PRODUTO;

}
